### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by jayvdb** [excitoon/tempfile2#1]
https://github.com/excitoon/tempfile2/releases is empty

**Comment by excitoon** [comment]
@jayvdb Why is this a problem? It shall be distributed through PyPI. However, I'd like to ask, is it useful somehow? Since these times I personally started to use `tempfile.TemporaryDirectory()` even for single files.

**Comment by jayvdb** [comment]
There is only a wheel at https://pypi.org/project/tempfile2/#files , not a source dist (tar.gz).

The source dist would normally contain the test files, so that they can be used to validate the package.

At the time I created this task, I was hoping to use this to package tempfile2 for openSUSE at https://build.opensuse.org/package/show/home:jayvdb:py-backports/python-tempfile2

Without a sdist on PyPI, I would need a tag on GitHub to know which versions of the files are "0.1.1".

**Comment by excitoon** [comment]
I see. It's good to understand. I will always make sdists for projects like
this.

**Comment by excitoon** [comment]
https://pypi.org/project/tempfile2/0.1.2/#files
